workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-v8
      - node-v10
      - node-v12

version: 2
jobs:
  node-base: &node-base
    docker:
      - image: node:latest@sha256:908e8182394cb5672465780ed45512d9b78dccd10d674e84158ea65b40bba755
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-cache-master-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Test
          command: npm test
      - save_cache:
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

  node-v8:
    <<: *node-base
    docker:
      - image: node:8@sha256:957cab2653bde49d195e0a98c6ae0c1700ed51eb94fce30faadaceacf331a0a1
  node-v10:
    <<: *node-base
    docker:
      - image: node:10@sha256:2c0459e6f7fb62543b4ca30d4efcd0edd860224c86187c808f1975e811be1f00
  node-v12:
    <<: *node-base
    docker:
      - image: node:12
