workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-v10
      - node-v12
      - node-v14

version: 2
jobs:
  node-base: &node-base
    docker:
      - image: node:latest@sha256:3992f9fa546e05b586b7e4c349a433b68212cffb86ccefd57c776051a59bf7ca
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-cache-master-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Test
          command: npm test
      - save_cache:
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

  node-v10:
    <<: *node-base
    docker:
      - image: node:10@sha256:df5e112285443181397aa633abe939002563dc6ef050f997ccd406914c260dc4
  node-v12:
    <<: *node-base
    docker:
      - image: node:12
  node-v14:
    <<: *node-base
    docker:
      - image: node:14
