workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-v10
      - node-v12
      - node-v13

version: 2
jobs:
  node-base: &node-base
    docker:
      - image: node:latest@sha256:b6dd69c9b7b24e7969f38785a3696a978bf20265dc801c52d450509fe7ddc8df
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-cache-master-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Test
          command: npm test
      - save_cache:
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

  node-v10:
    <<: *node-base
    docker:
      - image: node:10@sha256:63440af6b9b9a1ae4a821d7241c1e9b4a1bc854657d493611939513a951ee092
  node-v12:
    <<: *node-base
    docker:
      - image: node:12
  node-v13:
    <<: *node-base
    docker:
      - image: node:13
