workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-v8
      - node-v10
      - node-v12

version: 2
jobs:
  node-base: &node-base
    docker:
      - image: node:latest@sha256:90285adc307844b632965099129d1f4819300fd7be3bbec3d93c36eb91b6266c
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-cache-master-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Test
          command: npm test
      - save_cache:
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

  node-v8:
    <<: *node-base
    docker:
      - image: node:8@sha256:9f1271db6874a0570e00f39273003ff22c1d358c0c612f553c11c8727ce49426
  node-v10:
    <<: *node-base
    docker:
      - image: node:10@sha256:b050ae5bfcedc1bfd9ad8216c960115cb0f3d2e09ee4e844f80ed39a7632e4ed
  node-v12:
    <<: *node-base
    docker:
      - image: node:12
