'use strict';

module.exports = {
  "extends": "eslint:recommended",
  "env": {
    "browser": true,
    "node": true,
  },
  "globals": {
  },
  "rules": {
    // ## Possible Errors
    // The following rules point out areas where you might have made mistakes.
    // TODO: allow `while (true)`
    "no-constant-condition": 2,
    "no-extra-parens": 0,
    "no-inner-declarations": [2, "functions"],
    "valid-jsdoc": [1, {
      "requireReturn": false,
      "requireParamDescription": false,
      "requireReturnDescription": false,
      "prefer": {
        "returns": "return"
      },
      "preferType": {
        "Boolean": "boolean",
        "Number": "number",
        "String": "string",
        "Null": "null",
        "Undefined": "undefined",
      }
    }],

    // ## Best Practices
    // These are rules designed to prevent you from making mistakes.
    // They either prescribe a better way of doing something or help you avoid footguns.
    "accessor-pairs": 2,
    "array-callback-return": 2,
    "block-scoped-var": 2,
    "complexity": [1, 20],
    "consistent-return": 2,
    "curly": [2, "multi-line", "consistent"],
    "default-case": 2,
    "dot-location": [2, "property"],
    "dot-notation": 2,
    "eqeqeq": [2, "smart"],
    "guard-for-in": 0,
    "no-alert": 0,
    "no-caller": 2,
    "no-div-regex": 0,
    "no-else-return": 0,
    "no-empty-function": 0,
    "no-eq-null": 0,
    "no-eval": 2,
    "no-extend-native": 2,
    "no-extra-bind": 2,
    "no-extra-label": 2,
    "no-floating-decimal": 0,
    "no-implicit-coercion": [2, {"allow": ["!!"]}],
    "no-implicit-globals": 2,
    "no-implied-eval": 2,
    "no-invalid-this": 2,
    "no-iterator": 2,
    "no-labels": 2,
    "no-lone-blocks": 2,
    "no-loop-func": 2,
    "no-magic-numbers": [1, {"ignoreArrayIndexes": true}],
    "no-multi-spaces": 2,
    "no-multi-str": 2,
    "no-native-reassign": 2,
    "no-new": 0,
    "no-new-func": 2,
    "no-new-wrappers": 2,
    "no-octal-escape": 2,
    "no-param-reassign": [1, {"props": true}],
    "no-proto": 2,
    "no-redeclare": 2,
    "no-return-assign": 2,
    "no-script-url": 2,
    "no-self-assign": 2,
    "no-self-compare": 2,
    "no-sequences": 2,
    "no-throw-literal": 2,
    "no-unmodified-loop-condition": 2,
    "no-unused-expressions": 2,
    "no-useless-call": 2,
    "no-useless-concat": 2,
    "no-void": 2,
    "no-warning-comments": 0,
    "no-with": 2,
    "radix": 2,
    "vars-on-top": 0,
    "yoda": [2, "never", {"onlyEquality": true}],

    // ## Strict Mode
    // These rules relate to using strict mode and strict mode directives.
    "strict": [2, "global"],

    // ## Variables
    // These rules have to do with variable declarations.
    "init-declarations": 0,
    "no-catch-shadow": 2,
    "no-label-var": 2,
    "no-restricted-globals": 2,
    "no-shadow": 1,
    "no-shadow-restricted-names": 2,
    "no-undef-init": 2,
    "no-undefined": 0,
    "no-unused-vars": [2, {"args": "none"}],
    "no-use-before-define": [2, {"functions": false}],

    // ## Node.js and CommonJS
    // These rules are specific to JavaScript running on Node.js or using CommonJS in the browser.
    "callback-return": 0,
    "global-require": 2,
    "handle-callback-err": 2,
    "no-mixed-requires": 2,
    "no-new-require": 2,
    "no-path-concat": 2,
    "no-process-env": 2,
    "no-process-exit": 2,
    "no-restricted-modules": 2,
    "no-sync": 2,

    // ## Stylistic Issues
    // These rules are purely matters of style and are quite subjective.
    "array-bracket-spacing": [2, "never"],
    "block-spacing": [2, "always"],
    "brace-style": [2, "1tbs", {"allowSingleLine": true}],
    // allow `opt_foo` and `var_args`
    "camelcase": 0,
    "comma-spacing": [2, {"after": true, "before": false}],
    "comma-style": [2, "last" ],
    "computed-property-spacing": [2, "never"],
    "consistent-this": [2, "self"],
    "eol-last": 2,
    "func-names": 0,
    "func-style": 0,
    "id-blacklist": 2,
    "id-length": 0,
    // allow `opt_foo` and `var_args`
    "id-match": [2, "^(?:var_args|(?:opt_)?[a-zA-Z0-9]+_?|[_A-Z0-9]+)$"],
    "indent": [2, 2, {"SwitchCase": 1}],
    "jsx-quotes": 2,
    "key-spacing": 2,
    "keyword-spacing": [2, {"after": true, "before": true}],
    "linebreak-style": [2, "unix"],
    "lines-around-comment": 0,
    "max-depth": 2,
    "max-len": [2, {"code": 120}],
    "max-nested-callbacks": [2, 6],
    "max-params": [2, 4],
    "max-statements": [2, 24],
    "new-parens": 2,
    "newline-after-var": 0,
    "newline-before-return": 0,
    "newline-per-chained-call": 2,
    "no-array-constructor": 2,
    "no-bitwise": 0,
    "no-continue": 0,
    "no-inline-comments": 0,
    "no-lonely-if": 2,
    "no-multiple-empty-lines": [2, {"max": 2, "maxBOF": 0, "maxEOF": 0}],
    "no-negated-condition": 1,
    "no-nested-ternary": 1,
    "no-new-object": 2,
    "no-plusplus": 0,
    "no-restricted-syntax": 2,
    "no-spaced-func": 2,
    "no-ternary": 0,
    "no-trailing-spaces": 2,
    // for @private
    "no-underscore-dangle": 0,
    "no-unneeded-ternary": 2,
    "no-whitespace-before-property": 2,
    "object-curly-spacing": [2, "never"],
    "one-var": [2, "never"],
    "one-var-declaration-per-line": 0,
    "operator-assignment": [2, "always"],
    "operator-linebreak": [2, "after"],
    "padded-blocks": [2, "never"],
    "quote-props": [2, "as-needed"],
    "quotes": [2, "single", "avoid-escape"],
    "require-jsdoc": 0,
    "semi": 2,
    "semi-spacing": [2, {
      "after": true,
      "before": false,
    }],
    "sort-imports": 0,
    "sort-vars": 0,
    "space-before-blocks": 2,
    "space-before-function-paren": [2, "never"],
    "space-in-parens": [2, "never"],
    "space-infix-ops": 2,
    "space-unary-ops": 2,
    "spaced-comment": [2, "always"],
    "wrap-regex": 0,
  }
};
